logging:
  level:
    org.springframework.jdbc: DEBUG

spring:
    profiles:
      active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate.default_schema: 'spring_studies'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'

---
spring:
    config:
      activate:
        on-profile: test
    jpa:
      hibernate:
        ddl-auto: none
      database: h2
